In [3]:
import numpy as np

In [4]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [6]:
np.array([1,2,3,4], dtype=np.float)

array([1., 2., 3., 4.])

In [7]:
np.array([range(i, i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10, 2) #0~9까지 2step씩 표기한다.

array([0, 2, 4, 6, 8])

In [10]:
np.linspace(0, 100, 5, dtype=int) #0 ~ 100까지 5구간으로 균일분할 해라.

array([  0,  25,  50,  75, 100])

In [12]:
np.random.random((3,3)) #랜덤 함수 3행3열로 랜덤 값을 만들어라.

array([[0.58556265, 0.11483858, 0.93904192],
       [0.24059101, 0.73290311, 0.20425942],
       [0.49267918, 0.71095345, 0.68987398]])

In [13]:
np.random.randint(0, 10, (3,3)) # 0~9까지 3행 3열로 표기해라.

array([[4, 7, 9],
       [2, 7, 2],
       [7, 6, 3]])

In [14]:
np.random.normal(0, 1, (3,3)) #normal(평균, 표준편차, 3행 3열) : 정규분포  

array([[-1.62418129, -0.68344566,  0.6053072 ],
       [-1.29642402,  0.28266184,  0.68329463],
       [-0.22050222, -0.04857073, -0.20958429]])

In [16]:
np.random.seed(0) #랜텀 seed(0) 매번 동일한 랜덤 값을 사용하기 위하여.

arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(2,3))

print(arr1)
print(arr2)

[5 0 3 3 7 9]
[[3 5 2]
 [4 7 6]]


In [18]:
#슬라이싱
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr1[0:5:1] #[시작:종료:step]

array([0, 1, 2, 3, 4])

In [23]:
arr1[:5]

array([0, 1, 2, 3, 4])

In [24]:
arr1[2:9:2]

array([2, 4, 6, 8])

In [25]:
arr1[2::2]

array([2, 4, 6, 8])

In [26]:
arr1[::-1] #거꾸로 출력 하기

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [27]:
arr1[5::-1]

array([5, 4, 3, 2, 1, 0])

In [31]:
arr2 = np.arange(12).reshape(-1,4)

In [32]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
arr2[:3, :4]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
arr2[:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
#Numpy 배열 객체의 연결
list1 = [1,2,3]
list2 = [4,5,6]

In [41]:
arr1 = np.concatenate([list1, list2])

In [43]:
arr2 = arr1.reshape(-1, 3)

In [44]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.vstack([arr2, arr2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
np.random.seed(0)

arr2 = np.random.randint(1,10,(3,4))
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [ ]:
D

In [47]:
arr2

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [48]:
np.sum(arr2), arr2.sum()

(65, 65)

In [51]:
np.sum(arr2, axis=0), np.sum(arr2, axis=1)

(array([19, 13, 17, 16]), array([15, 21, 29]))

In [53]:
np.min(arr2, axis=0), np.max(arr2, axis=0)

(array([5, 1, 4, 3]), array([8, 8, 7, 9]))

In [56]:
np.mean(arr2, axis=0), np.std(arr2)

(array([6.33333333, 4.33333333, 5.66666667, 5.33333333]), 2.2530843057659626)

In [57]:
#Numpy 배열 객체와 브로드캐스팅

In [60]:
np.random.seed(0)
X = np.random.random((10,3))
X

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194]])

In [63]:
Xmean = X.mean(axis=0)
Xmean

array([0.52101579, 0.62614181, 0.59620338])

In [65]:
Xcentered = X - Xmean
Xcentered

array([[ 0.02779771,  0.08904756,  0.00655999],
       [ 0.02386739, -0.20248701,  0.04969073],
       [-0.08342858,  0.26563119,  0.36745938],
       [-0.13757427,  0.16558323, -0.06730846],
       [ 0.04702877,  0.29945483, -0.52516732],
       [-0.43388649, -0.60592341,  0.23641646],
       [ 0.25714096,  0.24387034,  0.38241496],
       [ 0.27814277, -0.16466245,  0.18432579],
       [-0.40274137,  0.01377921, -0.45285009],
       [ 0.42365312, -0.10429349, -0.18154144]])

In [66]:
#numpy 배열객체의 부울 배열과 마스킹 연산

In [68]:
np.random.seed(0)
X = np.random.randint(1,10, size=(3,4))
X

array([[6, 1, 4, 4],
       [8, 4, 6, 3],
       [5, 8, 7, 9]])

In [69]:
(X > 5) & (X< 8)

array([[ True, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False]])

In [70]:
np.sum((X>5) & (X<8))

3

In [71]:
X[(X>5) & (X<8)]

array([6, 6, 7])

In [72]:
#Numpy 배열 객체와 팬시 인덱싱

In [75]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
row = np.array([0,1,2])
col = np.array([1,2,3])

In [80]:
X[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [86]:
np.random.seed(0)
arr1 = np.random.random((3,3))
arr1

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [92]:
x = np.array(np.random.randint(10, size=5))
x

array([1, 5, 9, 8, 9])

In [94]:
np.sort(x)

array([1, 5, 8, 9, 9])

array([1, 5, 8, 9, 9])

In [74]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])